// <auto-generated />
using System;
using ECommerceProjectAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceProjectAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203212802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerceProjectAPI.Models.Address", b =>
                {
                    b.Property<int>("addressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("addressId"));

                    b.Property<string>("ApartmentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("addressName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("addressId");

                    b.HasIndex("userId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Branch", b =>
                {
                    b.Property<int>("branchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("branchId"));

                    b.Property<string>("branchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("mgrId")
                        .HasColumnType("int");

                    b.Property<decimal>("totalSales")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("branchId");

                    b.HasIndex("mgrId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Cart", b =>
                {
                    b.Property<int>("cartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cartId"));

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.HasKey("cartId");

                    b.HasIndex("customerId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.CartItem", b =>
                {
                    b.Property<int>("cartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cartItemId"));

                    b.Property<int>("cartId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("cartItemId");

                    b.HasIndex("cartId");

                    b.HasIndex("productId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderId"));

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("orderStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("orderId");

                    b.HasIndex("customerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("orderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("orderItemId"));

                    b.Property<decimal>("discountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("orderItemId");

                    b.HasIndex("orderId");

                    b.HasIndex("productId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("productId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("productCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("productPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("salesPersonId")
                        .HasColumnType("int");

                    b.Property<int>("stockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("productId");

                    b.HasIndex("salesPersonId");

                    b.ToTable("Products", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.BookProduct", b =>
                {
                    b.HasBaseType("ECommerceProjectAPI.Models.Product");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberOfPages")
                        .HasColumnType("int");

                    b.Property<string>("publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Books", (string)null);
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.LaptopProduct", b =>
                {
                    b.HasBaseType("ECommerceProjectAPI.Models.Product");

                    b.Property<string>("processor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ramSizeGB")
                        .HasColumnType("int");

                    b.Property<float>("screenSizeInches")
                        .HasColumnType("real");

                    b.ToTable("Laptops", (string)null);
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.PhoneProduct", b =>
                {
                    b.HasBaseType("ECommerceProjectAPI.Models.Product");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cameraMegapixels")
                        .HasColumnType("int");

                    b.Property<float>("screenSizeInches")
                        .HasColumnType("real");

                    b.Property<int>("storageCapacityGB")
                        .HasColumnType("int");

                    b.ToTable("Phones", (string)null);
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Admin", b =>
                {
                    b.HasBaseType("ECommerceProjectAPI.Models.User");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Customer", b =>
                {
                    b.HasBaseType("ECommerceProjectAPI.Models.User");

                    b.Property<decimal>("balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("customerLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Employee", b =>
                {
                    b.HasBaseType("ECommerceProjectAPI.Models.User");

                    b.Property<int?>("branchId")
                        .HasColumnType("int");

                    b.Property<decimal>("salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("supervisorId")
                        .HasColumnType("int");

                    b.Property<decimal>("totalSales")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("branchId");

                    b.HasIndex("supervisorId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Address", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.User", "user")
                        .WithMany("addresses")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Branch", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.Employee", "Manager")
                        .WithMany("managedBranches")
                        .HasForeignKey("mgrId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Cart", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.Customer", "customer")
                        .WithOne("cart")
                        .HasForeignKey("ECommerceProjectAPI.Models.Cart", "customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.CartItem", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.Cart", "cart")
                        .WithMany("Items")
                        .HasForeignKey("cartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceProjectAPI.Models.Product", "product")
                        .WithMany("cartItems")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("cart");

                    b.Navigation("product");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Order", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.Customer", "customer")
                        .WithMany("Orders")
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.OrderItem", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.Order", "order")
                        .WithMany("Items")
                        .HasForeignKey("orderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceProjectAPI.Models.Product", "product")
                        .WithMany("orderItems")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Product", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.Employee", "trackingBy")
                        .WithMany("trackedProducts")
                        .HasForeignKey("salesPersonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("trackingBy");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.BookProduct", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("ECommerceProjectAPI.Models.BookProduct", "productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.LaptopProduct", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("ECommerceProjectAPI.Models.LaptopProduct", "productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.PhoneProduct", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.Product", null)
                        .WithOne()
                        .HasForeignKey("ECommerceProjectAPI.Models.PhoneProduct", "productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Admin", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.User", null)
                        .WithOne()
                        .HasForeignKey("ECommerceProjectAPI.Models.Admin", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Customer", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.User", null)
                        .WithOne()
                        .HasForeignKey("ECommerceProjectAPI.Models.Customer", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Employee", b =>
                {
                    b.HasOne("ECommerceProjectAPI.Models.Branch", "branch")
                        .WithMany("Employees")
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ECommerceProjectAPI.Models.Employee", "supervisor")
                        .WithMany("supervisorOf")
                        .HasForeignKey("supervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ECommerceProjectAPI.Models.User", null)
                        .WithOne()
                        .HasForeignKey("ECommerceProjectAPI.Models.Employee", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("branch");

                    b.Navigation("supervisor");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Branch", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Product", b =>
                {
                    b.Navigation("cartItems");

                    b.Navigation("orderItems");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.User", b =>
                {
                    b.Navigation("addresses");
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("cart")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerceProjectAPI.Models.Employee", b =>
                {
                    b.Navigation("managedBranches");

                    b.Navigation("supervisorOf");

                    b.Navigation("trackedProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
